import { 
  collection, 
  doc, 
  getDocs, 
  getDoc, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  query, 
  where, 
  orderBy, 
  Timestamp,
  QueryConstraint
} from 'firebase/firestore';
import { db } from '../config/firebase';
import { ClassModel, ClassStatus } from '../../types';
import { 
  validateDeleteClass, 
  cascadeDeleteClass, 
  cascadeUpdateClassName 
} from './dataIntegrityService';

const COLLECTION_NAME = 'classes';

// NOTE: Session generation is now handled by Cloud Functions (onClassCreate trigger)
// See: functions/src/triggers/classTriggers.ts

export class ClassService {
  
  // Get all classes with optional filters
  static async getClasses(filters?: {
    status?: ClassStatus;
    teacherId?: string;
    searchTerm?: string;
  }): Promise<ClassModel[]> {
    try {
      const constraints: QueryConstraint[] = [];
      
      if (filters?.status) {
        constraints.push(where('status', '==', filters.status));
      }
      
      if (filters?.teacherId) {
        constraints.push(where('teacherId', '==', filters.teacherId));
      }
      
      constraints.push(orderBy('createdAt', 'desc'));
      
      const q = query(collection(db, COLLECTION_NAME), ...constraints);
      const snapshot = await getDocs(q);
      
      let classes = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data(),
        startDate: doc.data().startDate?.toDate().toISOString().split('T')[0] || '',
        endDate: doc.data().endDate?.toDate().toISOString().split('T')[0] || ''
      })) as ClassModel[];
      
      // Client-side search if searchTerm provided
      if (filters?.searchTerm) {
        const term = filters.searchTerm.toLowerCase();
        classes = classes.filter(c => 
          c.name.toLowerCase().includes(term)
        );
      }
      
      return classes;
    } catch (error) {
      console.error('Error getting classes:', error);
      throw error;
    }
  }
  
  // Get single class by ID
  static async getClassById(id: string): Promise<ClassModel | null> {
    try {
      const docRef = doc(db, COLLECTION_NAME, id);
      const docSnap = await getDoc(docRef);
      
      if (docSnap.exists()) {
        return {
          id: docSnap.id,
          ...docSnap.data(),
          startDate: docSnap.data().startDate?.toDate().toISOString().split('T')[0] || '',
          endDate: docSnap.data().endDate?.toDate().toISOString().split('T')[0] || ''
        } as ClassModel;
      }
      
      return null;
    } catch (error) {
      console.error('Error getting class:', error);
      throw error;
    }
  }
  
  // Create new class
  static async createClass(classData: Omit<ClassModel, 'id'>): Promise<string> {
    try {
      const dataToSave: any = {
        ...classData,
        startDate: classData.startDate ? Timestamp.fromDate(new Date(classData.startDate)) : null,
        endDate: classData.endDate ? Timestamp.fromDate(new Date(classData.endDate)) : null,
        history: [{
          id: `HIST_${Date.now()}`,
          date: Timestamp.now(),
          type: 'Tạo lớp',
          description: `Lớp học ${classData.name} được tạo`,
          staffId: '',
          staffName: 'System'
        }],
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now()
      };
      
      const docRef = await addDoc(collection(db, COLLECTION_NAME), dataToSave);
      
      // NOTE: Sessions are now auto-generated by Cloud Function (onClassCreate)
      // See: functions/src/triggers/classTriggers.ts
      
      return docRef.id;
    } catch (error) {
      console.error('Error creating class:', error);
      throw error;
    }
  }
  
  // Update class
  static async updateClass(id: string, updates: Partial<ClassModel>): Promise<void> {
    try {
      const docRef = doc(db, COLLECTION_NAME, id);
      
      const updateData: any = {
        ...updates,
        updatedAt: Timestamp.now()
      };
      
      // Convert date strings to Timestamps (handle empty strings)
      if (updates.startDate !== undefined) {
        updateData.startDate = updates.startDate ? Timestamp.fromDate(new Date(updates.startDate)) : null;
      }
      
      if (updates.endDate !== undefined) {
        updateData.endDate = updates.endDate ? Timestamp.fromDate(new Date(updates.endDate)) : null;
      }
      
      await updateDoc(docRef, updateData);
      
      // Cascade update className to students if name changed
      if (updates.name) {
        await cascadeUpdateClassName(id, updates.name);
      }
    } catch (error) {
      console.error('Error updating class:', error);
      throw error;
    }
  }
  
  // Delete class with validation and cascade
  static async deleteClass(id: string, forceDelete: boolean = false): Promise<{
    success: boolean;
    message: string;
    cascadeResult?: { studentsUpdated: number; workSessionsUpdated: number };
  }> {
    try {
      // Get class info first
      const classData = await this.getClassById(id);
      
      // Validate before delete
      if (!forceDelete) {
        const validation = await validateDeleteClass(id);
        if (!validation.canDelete) {
          return {
            success: false,
            message: validation.reason || 'Không thể xóa lớp học',
          };
        }
      }
      
      // Cascade updates (clear references in students/work sessions)
      const cascadeResult = await cascadeDeleteClass(id, classData?.name);
      
      // Delete the class
      const docRef = doc(db, COLLECTION_NAME, id);
      await deleteDoc(docRef);
      
      return {
        success: true,
        message: `Đã xóa lớp học. ${cascadeResult.studentsUpdated} học viên và ${cascadeResult.workSessionsUpdated} buổi dạy đã được cập nhật.`,
        cascadeResult,
      };
    } catch (error) {
      console.error('Error deleting class:', error);
      throw error;
    }
  }
  
  // Simple delete (backward compatibility)
  static async deleteClassSimple(id: string): Promise<void> {
    const result = await this.deleteClass(id, true);
    if (!result.success) {
      throw new Error(result.message);
    }
  }
  
  // Add history entry to class
  static async addClassHistory(
    classId: string, 
    historyEntry: {
      type: string;
      description: string;
      staffId: string;
      staffName: string;
    }
  ): Promise<void> {
    try {
      const classData = await this.getClassById(classId);
      if (!classData) throw new Error('Class not found');
      
      const docRef = doc(db, COLLECTION_NAME, classId);
      const currentHistory = (classData as any).history || [];
      
      const newEntry = {
        id: `HIST_${Date.now()}`,
        date: Timestamp.now(),
        ...historyEntry
      };
      
      await updateDoc(docRef, {
        history: [...currentHistory, newEntry],
        updatedAt: Timestamp.now()
      });
    } catch (error) {
      console.error('Error adding class history:', error);
      throw error;
    }
  }
  
  // Update class progress
  static async updateClassProgress(classId: string, progress: string): Promise<void> {
    try {
      await this.updateClass(classId, { progress });
      await this.addClassHistory(classId, {
        type: 'Cập nhật tiến độ',
        description: `Tiến độ cập nhật: ${progress}`,
        staffId: '',
        staffName: 'System'
      });
    } catch (error) {
      console.error('Error updating class progress:', error);
      throw error;
    }
  }
  
  // Get classes by teacher
  static async getClassesByTeacher(teacherId: string): Promise<ClassModel[]> {
    return this.getClasses({ teacherId });
  }
  
  // Get active classes
  static async getActiveClasses(): Promise<ClassModel[]> {
    return this.getClasses({ status: ClassStatus.STUDYING });
  }
}
