/**
 * Work Generator Service
 * Tự động tạo công dựa theo TKB và lịch nghỉ
 */

import { collection, getDocs, addDoc, query, where } from 'firebase/firestore';
import { db } from '../config/firebase';
import { ClassModel } from '../../types';

interface GeneratedWorkSession {
  staffName: string;
  staffId?: string;
  position: string;
  date: string;
  timeStart: string;
  timeEnd: string;
  classId: string;
  className: string;
  type: 'Dạy chính' | 'Trợ giảng' | 'Nhận xét';
  status: 'Chờ xác nhận';
  autoGenerated: boolean;
}

// Parse schedule string to get days and time
const parseSchedule = (schedule: string): { days: number[]; timeStart: string; timeEnd: string } => {
  if (!schedule) return { days: [], timeStart: '', timeEnd: '' };
  
  // Parse time (e.g., "18:00-19:00" or "17:30 - 19:00")
  const timeMatch = schedule.match(/(\d{1,2}[h:]?\d{2})\s*-\s*(\d{1,2}[h:]?\d{2})/);
  let timeStart = '';
  let timeEnd = '';
  if (timeMatch) {
    timeStart = timeMatch[1].replace('h', ':');
    timeEnd = timeMatch[2].replace('h', ':');
  }
  
  // Parse days (e.g., "Thứ 2, 4" -> [2, 4])
  const dayMatch = schedule.match(/Th[ứử]\s*(\d)(?:\s*,\s*(\d))?/i);
  const days: number[] = [];
  if (dayMatch) {
    if (dayMatch[1]) days.push(parseInt(dayMatch[1]));
    if (dayMatch[2]) days.push(parseInt(dayMatch[2]));
  }
  
  return { days, timeStart, timeEnd };
};

// Get dates for a specific day of week within a date range
const getDatesForDayOfWeek = (dayOfWeek: number, startDate: Date, endDate: Date): Date[] => {
  const dates: Date[] = [];
  const current = new Date(startDate);
  
  // dayOfWeek: 2 = Monday, 3 = Tuesday, etc. (Vietnamese style)
  // JavaScript: 0 = Sunday, 1 = Monday, etc.
  const jsDayOfWeek = dayOfWeek === 7 ? 0 : dayOfWeek - 1;
  
  // Find the first occurrence
  while (current.getDay() !== jsDayOfWeek) {
    current.setDate(current.getDate() + 1);
  }
  
  // Collect all dates
  while (current <= endDate) {
    dates.push(new Date(current));
    current.setDate(current.getDate() + 7);
  }
  
  return dates;
};

// Format date to YYYY-MM-DD
const formatDate = (date: Date): string => {
  return date.toISOString().split('T')[0];
};

// Get holidays from Firebase
export const getHolidays = async (startDate: string, endDate: string): Promise<string[]> => {
  try {
    const snapshot = await getDocs(collection(db, 'holidays'));
    const holidays: string[] = [];
    
    snapshot.docs.forEach(doc => {
      const data = doc.data();
      const holidayDate = data.date?.toDate?.()?.toISOString().split('T')[0] || data.date;
      if (holidayDate >= startDate && holidayDate <= endDate) {
        holidays.push(holidayDate);
      }
    });
    
    return holidays;
  } catch (error) {
    console.error('Error getting holidays:', error);
    return [];
  }
};

// Check if work session already exists
const checkExistingSession = async (
  staffName: string,
  date: string,
  className: string
): Promise<boolean> => {
  try {
    const q = query(
      collection(db, 'workSessions'),
      where('staffName', '==', staffName),
      where('date', '==', date),
      where('className', '==', className)
    );
    const snapshot = await getDocs(q);
    return !snapshot.empty;
  } catch (error) {
    console.error('Error checking existing session:', error);
    return false;
  }
};

// Generate work sessions for a week
export const generateWorkSessionsForWeek = async (
  weekStartDate: Date
): Promise<{ created: number; skipped: number; errors: string[] }> => {
  const result = { created: 0, skipped: 0, errors: [] as string[] };
  
  try {
    // Get week end date (Friday)
    const weekEndDate = new Date(weekStartDate);
    weekEndDate.setDate(weekEndDate.getDate() + 4);
    
    const startDateStr = formatDate(weekStartDate);
    const endDateStr = formatDate(weekEndDate);
    
    // Get holidays
    const holidays = await getHolidays(startDateStr, endDateStr);
    
    // Get all active classes
    const classesSnapshot = await getDocs(collection(db, 'classes'));
    const classes: ClassModel[] = classesSnapshot.docs
      .map(doc => ({ id: doc.id, ...doc.data() } as ClassModel))
      .filter(cls => cls.status === 'Đang học');
    
    // Generate sessions for each class
    for (const cls of classes) {
      const { days, timeStart, timeEnd } = parseSchedule(cls.schedule || '');
      
      if (days.length === 0 || !timeStart || !timeEnd) {
        continue;
      }
      
      // For each scheduled day
      for (const dayOfWeek of days) {
        const dates = getDatesForDayOfWeek(dayOfWeek, weekStartDate, weekEndDate);
        
        for (const date of dates) {
          const dateStr = formatDate(date);
          
          // Skip holidays
          if (holidays.includes(dateStr)) {
            result.skipped++;
            continue;
          }
          
          // Generate for Vietnamese teacher
          if (cls.teacher) {
            const exists = await checkExistingSession(cls.teacher, dateStr, cls.name);
            if (!exists) {
              const session: GeneratedWorkSession = {
                staffName: cls.teacher,
                position: 'Giáo viên Việt',
                date: dateStr,
                timeStart,
                timeEnd,
                classId: cls.id,
                className: cls.name,
                type: 'Dạy chính',
                status: 'Chờ xác nhận',
                autoGenerated: true,
              };
              
              await addDoc(collection(db, 'workSessions'), {
                ...session,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              });
              result.created++;
            } else {
              result.skipped++;
            }
          }
          
          // Generate for foreign teacher (if assigned)
          if (cls.foreignTeacher) {
            const exists = await checkExistingSession(cls.foreignTeacher, dateStr, cls.name);
            if (!exists) {
              const session: GeneratedWorkSession = {
                staffName: cls.foreignTeacher,
                position: 'Giáo viên Nước ngoài',
                date: dateStr,
                timeStart,
                timeEnd,
                classId: cls.id,
                className: cls.name,
                type: 'Dạy chính',
                status: 'Chờ xác nhận',
                autoGenerated: true,
              };
              
              await addDoc(collection(db, 'workSessions'), {
                ...session,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              });
              result.created++;
            } else {
              result.skipped++;
            }
          }
          
          // Generate for assistant (if assigned)
          if (cls.assistant) {
            const exists = await checkExistingSession(cls.assistant, dateStr, cls.name);
            if (!exists) {
              const session: GeneratedWorkSession = {
                staffName: cls.assistant,
                position: 'Trợ giảng',
                date: dateStr,
                timeStart,
                timeEnd,
                classId: cls.id,
                className: cls.name,
                type: 'Trợ giảng',
                status: 'Chờ xác nhận',
                autoGenerated: true,
              };
              
              await addDoc(collection(db, 'workSessions'), {
                ...session,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              });
              result.created++;
            } else {
              result.skipped++;
            }
          }
        }
      }
    }
    
    return result;
  } catch (error: any) {
    console.error('Error generating work sessions:', error);
    result.errors.push(error.message || 'Unknown error');
    return result;
  }
};

// Generate work sessions for current week
export const generateWorkSessionsForCurrentWeek = async () => {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const diff = today.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1); // Monday
  const monday = new Date(today.setDate(diff));
  monday.setHours(0, 0, 0, 0);
  
  return generateWorkSessionsForWeek(monday);
};
